name: Release

on:
  push:
    tags: [ 'v*' ]

jobs:
  pre-build:
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create-release.outputs.upload_url }}
      tag: ${{ steps.tag.outputs.tag }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go 1.15
        uses: actions/setup-go@v1
        with:
          go-version: 1.15

      - name: Download Go Dependencies
        run: go mod download

      - name: Build
        run: go build -v -o ./test ./main

      - name: Get Tag
        id: tag
        run: |
          tag=$(echo ${{ github.ref }} | cut -dv -f2)
          echo "::set-output name=tag::$tag"

      - name: Create Release
        id: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: pixiv-api-${{ steps.tag.outputs.tag }}
          draft: false
          prerelease: false

  build:
    runs-on: ubuntu-latest
    needs: pre-build
    strategy:
      matrix:
        platform-os: [linux, windows]
        platform-arch: [amd64]
        include:
          - platform-os: windows
            ext: .exe
          - platform-os: linux
            platform-arch: amd64
            push-docker: true
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go 1.15
        uses: actions/setup-go@v1
        with:
          go-version: 1.15

      - name: Download Go Dependencies
        run: go mod download

      - name: Build ${{ matrix.platform-os }} ${{ matrix.platform-arch }} target
        run: |
          CGO_ENABLED=0 GOOS=${{ matrix.platform-os }} GOARCH=${{ matrix.platform-arch }} \
          go build -ldflags="-s -w" -o \
          build/${{ matrix.platform-os }}-${{ matrix.platform-arch }}/pixiv-api${{ matrix.ext }} ./main

      - name: Upload Release ${{ matrix.platform-os }} ${{ matrix.platform-arch }} Target
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.pre-build.outputs.upload_url }}
          asset_path: build/${{ matrix.platform-os }}-${{ matrix.platform-arch }}/pixiv-api${{ matrix.ext }}
          asset_name: pixiv-api-${{ matrix.platform-os }}-${{ matrix.platform-arch }}-v${{ needs.pre-build.outputs.tag }}${{ matrix.ext }}
          asset_content_type: application/octet-stream

      - name: Chmod for pixiv-api-linux-amd64
        if: ${{ matrix.push-docker == true }}
        run: chmod u+x build/linux-amd64/pixiv-api

      - name: Login to Github Hub
        if: ${{ matrix.push-docker == true }}
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to Github Package
        if: ${{ matrix.push-docker == true }}
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Docker
        if: ${{ matrix.push-docker == true }}
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            ${{ secrets.DOCKER_USERNAME }}/pixiv-api
            ghcr.io/${{ github.repository }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}

      - name: Build and Push Docker Iamge
        if: ${{ matrix.push-docker == true }}
        uses: docker/build-push-action@v2
        with:
          context: ./build/linux-amd64
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}